### ISSUE TITLE
Does `cryptography` version still need to be fixated at 38.0.4?

### ISSUE THREAD

**Issue by dmalan** [cs50/server#32]
https://github.com/cs50/server/blob/583b715dfd61657a895c3217ec4327eae86e2270/Dockerfile#L32-L34

**Comment by rongxin-liu** [comment]
No longer needed.
[https://github.com/cs50/server/commit/b46c2464c56d5426fd6970672dc0b5f93ab65d6e](https://github.com/cs50/server/commit/b46c2464c56d5426fd6970672dc0b5f93ab65d6e)
