### ISSUE TITLE
Unable to download headers-more-nginx-module from GitHub using wget

### ISSUE THREAD

**Issue by rongxin-liu** [cs50/server#38]

**Comment by rongxin-liu** [comment]
https://github.com/cs50/server/blob/main/Dockerfile#L37
https://github.com/cs50/server/actions/runs/6002746621/job/16279739354#step:5:893

**Comment by dmalan** [comment]
Hm, URL still seems alive, https://github.com/openresty/headers-more-nginx-module/archive/v0.34.tar.gz?

**Comment by rongxin-liu** [comment]
I suspect it might be a GitHub issue, all wget commands are failing when trying to download archive from GitHub.

**Comment by rongxin-liu** [comment]
Resolved: https://github.com/cs50/server/commit/5cd865bccaa2409026ab8a1da73015d8c4397d59
Cause of issue: https://github.com/orgs/community/discussions/65227#discussioncomment-6848413
