### ISSUE TITLE
Persistent Server Error

### ISSUE THREAD

**Issue by RexRowan** [cs50/server#40]
![Screenshot - 05_01_2024 , 08_51_01](https://github.com/cs50/server/assets/4164511/5f99aa7e-4c40-4815-acfd-110d3d78ec24)
![Screenshot - 05_01_2024 , 08_51_18](https://github.com/cs50/server/assets/4164511/a2011a3b-3c5b-4111-8ffb-6f8255297b98)

**Comment by dmalan** [comment]
Afraid this isn't enough detail to diagnose! Be sure to click **Technical details for the administor of this website**!

**Comment by RexRowan** [comment]
![Screenshot - 05_01_2024 , 13_28_51](https://github.com/cs50/server/assets/4164511/153be4f9-b79c-43be-bed7-1f23a83fe0ec)

**Comment by RexRowan** [comment]
If I click on the Gradebook link, by default it leads to https://cs50.me/cs50w/ and the 404 page. 

If I add www in front of the cs50.me then it leads to the second error message.

**Comment by rongxin-liu** [comment]
Thank you for reporting. Please try again and see if the issue persists.

**Comment by RexRowan** [comment]
yes, still 404 when clicking on Gradebook

**Comment by rongxin-liu** [comment]
> yes, still 404 when clicking on Gradebook

Can you try visiting https://cs50.me/cs50w in a private window? This URL loads ok on my end.

**Comment by RexRowan** [comment]
Yes, the link you provided works, it also works from the Gradebook links of other courses. But the CSW one still shows 404, strange.

**Comment by RexRowan** [comment]
![Screenshot - 05_01_2024 , 15_17_50](https://github.com/cs50/server/assets/4164511/245fba98-2c02-49de-aa00-b04a8655fdb8)

**Comment by rongxin-liu** [comment]
Can you please visit [cs50.me/cs50w](https://cs50.me/cs50w) instead of [cs50.me/cs50w/](https://cs50.me/cs50w/)?

**Comment by rongxin-liu** [comment]
If you are accessing CS50 Web from cs50.me, you shouldn't be accessing that URL!

**Comment by RexRowan** [comment]
Progress! The first link rendered a Github 404 page. 

The original link yielded the same 404 result in in cognito window too. 

![Screenshot - 05_01_2024 , 15_19_57](https://github.com/cs50/server/assets/4164511/da98d059-12ba-442a-bb14-2c67f3136324)

**Comment by RexRowan** [comment]
I'm accessing cs50.me from CS50 Web

**Comment by rongxin-liu** [comment]
Can you click https://cs50.me/cs50w?

**Comment by RexRowan** [comment]
Ok, the first link work now

**Comment by RexRowan** [comment]
yes, the link works

**Comment by RexRowan** [comment]
Ah, all you need to do is get rid of the '/' at the end.
